# coding: utf-8

"""
    Aliseeks API

    AliExpress product searching and product details retrieval API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import aliseeksapi
from aliseeksapi.api.search_api import SearchApi  # noqa: E501
from aliseeksapi.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = aliseeksapi.api.search_api.SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_realtime_search(self):
        """Test case for realtime_search

        Searches AliExpress in realtime   # noqa: E501
        """
        pass

    def test_search(self):
        """Test case for search

        Searches AliExpress in non-realtime. Uses the Aliseeks.com datasource which is continually updated from AliExpress.   # noqa: E501
        """
        pass

    def test_search_best_selling(self):
        """Test case for search_best_selling

        Retrieves best selling products from AliExpress in realtime.   # noqa: E501
        """
        pass

    def test_search_by_image(self):
        """Test case for search_by_image

        Searches AliExpress by image in realtime.   # noqa: E501
        """
        pass

    def test_upload_image_by_url(self):
        """Test case for upload_image_by_url

        Uploads an image to AliExpress to allow it to be used in the image search endpoint   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
