# coding: utf-8

"""
    Aliseeks API

    AliExpress product searching and product details retrieval API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import aliseeksapi
from aliseeksapi.api.products_api import ProductsApi  # noqa: E501
from aliseeksapi.rest import ApiException


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = aliseeksapi.api.products_api.ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_product(self):
        """Test case for get_product

        Get products details as an aggregated request from AliExpress in realtime.   # noqa: E501
        """
        pass

    def test_get_product_details(self):
        """Test case for get_product_details

        Gets product details from AliExpress in realtime.   # noqa: E501
        """
        pass

    def test_get_product_html_description(self):
        """Test case for get_product_html_description

        Get product HTML description from AliExpress in realtime.   # noqa: E501
        """
        pass

    def test_get_product_shipping(self):
        """Test case for get_product_shipping

        Gets product shipping information AliExpress in realtime.   # noqa: E501
        """
        pass

    def test_get_product_skus(self):
        """Test case for get_product_skus

        Gets product skus / variation information from AliExpress in realtime.   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
