# coding: utf-8

"""
    Aliseeks API

    AliExpress product searching and product details retrieval API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import aliseeksapi
from aliseeksapi.models.product import Product  # noqa: E501
from aliseeksapi.rest import ApiException


class TestProduct(unittest.TestCase):
    """Product unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProduct(self):
        """Test Product"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aliseeksapi.models.product.Product()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
