# coding: utf-8

"""
    Aliseeks API

    AliExpress product searching and product details retrieval API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import aliseeksapi
from aliseeksapi.models.search_item_seller import SearchItemSeller  # noqa: E501
from aliseeksapi.rest import ApiException


class TestSearchItemSeller(unittest.TestCase):
    """SearchItemSeller unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchItemSeller(self):
        """Test SearchItemSeller"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aliseeksapi.models.search_item_seller.SearchItemSeller()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
