# coding: utf-8

"""
    Aliseeks API

    AliExpress product searching and product details retrieval API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Product(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'category_id': 'str',
        'company_id': 'str',
        'seller_id': 'str',
        'title': 'str',
        'status_id': 'int',
        'status': 'str',
        'count_per_lot': 'int',
        'wish_list_count': 'int',
        'unit': 'str',
        'multi_unit': 'str',
        'seller': 'ProductSeller',
        'reviews': 'ProductReviews',
        'trade': 'TradeInformation',
        'promotion': 'ProductPromotion',
        'product_images': 'list[str]',
        'attributes': 'list[ProductAttribute]',
        'html_description': 'str',
        'price_summary': 'PriceSummary',
        'prices': 'list[SkuPriceOption]',
        'shipping': 'list[ProductShippingOptions]'
    }

    attribute_map = {
        'id': 'id',
        'category_id': 'categoryId',
        'company_id': 'companyId',
        'seller_id': 'sellerId',
        'title': 'title',
        'status_id': 'statusId',
        'status': 'status',
        'count_per_lot': 'countPerLot',
        'wish_list_count': 'wishListCount',
        'unit': 'unit',
        'multi_unit': 'multiUnit',
        'seller': 'seller',
        'reviews': 'reviews',
        'trade': 'trade',
        'promotion': 'promotion',
        'product_images': 'productImages',
        'attributes': 'attributes',
        'html_description': 'htmlDescription',
        'price_summary': 'priceSummary',
        'prices': 'prices',
        'shipping': 'shipping'
    }

    def __init__(self, id=None, category_id=None, company_id=None, seller_id=None, title=None, status_id=None, status=None, count_per_lot=None, wish_list_count=None, unit=None, multi_unit=None, seller=None, reviews=None, trade=None, promotion=None, product_images=None, attributes=None, html_description=None, price_summary=None, prices=None, shipping=None):  # noqa: E501
        """Product - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._category_id = None
        self._company_id = None
        self._seller_id = None
        self._title = None
        self._status_id = None
        self._status = None
        self._count_per_lot = None
        self._wish_list_count = None
        self._unit = None
        self._multi_unit = None
        self._seller = None
        self._reviews = None
        self._trade = None
        self._promotion = None
        self._product_images = None
        self._attributes = None
        self._html_description = None
        self._price_summary = None
        self._prices = None
        self._shipping = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if category_id is not None:
            self.category_id = category_id
        if company_id is not None:
            self.company_id = company_id
        if seller_id is not None:
            self.seller_id = seller_id
        if title is not None:
            self.title = title
        if status_id is not None:
            self.status_id = status_id
        if status is not None:
            self.status = status
        if count_per_lot is not None:
            self.count_per_lot = count_per_lot
        if wish_list_count is not None:
            self.wish_list_count = wish_list_count
        if unit is not None:
            self.unit = unit
        if multi_unit is not None:
            self.multi_unit = multi_unit
        if seller is not None:
            self.seller = seller
        if reviews is not None:
            self.reviews = reviews
        if trade is not None:
            self.trade = trade
        if promotion is not None:
            self.promotion = promotion
        if product_images is not None:
            self.product_images = product_images
        if attributes is not None:
            self.attributes = attributes
        if html_description is not None:
            self.html_description = html_description
        if price_summary is not None:
            self.price_summary = price_summary
        if prices is not None:
            self.prices = prices
        if shipping is not None:
            self.shipping = shipping

    @property
    def id(self):
        """Gets the id of this Product.  # noqa: E501

        The AliExpress item ID   # noqa: E501

        :return: The id of this Product.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Product.

        The AliExpress item ID   # noqa: E501

        :param id: The id of this Product.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def category_id(self):
        """Gets the category_id of this Product.  # noqa: E501

        The item category   # noqa: E501

        :return: The category_id of this Product.  # noqa: E501
        :rtype: str
        """
        return self._category_id

    @category_id.setter
    def category_id(self, category_id):
        """Sets the category_id of this Product.

        The item category   # noqa: E501

        :param category_id: The category_id of this Product.  # noqa: E501
        :type: str
        """

        self._category_id = category_id

    @property
    def company_id(self):
        """Gets the company_id of this Product.  # noqa: E501

        The company ID   # noqa: E501

        :return: The company_id of this Product.  # noqa: E501
        :rtype: str
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """Sets the company_id of this Product.

        The company ID   # noqa: E501

        :param company_id: The company_id of this Product.  # noqa: E501
        :type: str
        """

        self._company_id = company_id

    @property
    def seller_id(self):
        """Gets the seller_id of this Product.  # noqa: E501

        The seller ID   # noqa: E501

        :return: The seller_id of this Product.  # noqa: E501
        :rtype: str
        """
        return self._seller_id

    @seller_id.setter
    def seller_id(self, seller_id):
        """Sets the seller_id of this Product.

        The seller ID   # noqa: E501

        :param seller_id: The seller_id of this Product.  # noqa: E501
        :type: str
        """

        self._seller_id = seller_id

    @property
    def title(self):
        """Gets the title of this Product.  # noqa: E501

        The subject / title of the item   # noqa: E501

        :return: The title of this Product.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Product.

        The subject / title of the item   # noqa: E501

        :param title: The title of this Product.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def status_id(self):
        """Gets the status_id of this Product.  # noqa: E501

        The AliExpress status ID   # noqa: E501

        :return: The status_id of this Product.  # noqa: E501
        :rtype: int
        """
        return self._status_id

    @status_id.setter
    def status_id(self, status_id):
        """Sets the status_id of this Product.

        The AliExpress status ID   # noqa: E501

        :param status_id: The status_id of this Product.  # noqa: E501
        :type: int
        """

        self._status_id = status_id

    @property
    def status(self):
        """Gets the status of this Product.  # noqa: E501

        The AliExpress status   # noqa: E501

        :return: The status of this Product.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Product.

        The AliExpress status   # noqa: E501

        :param status: The status of this Product.  # noqa: E501
        :type: str
        """
        allowed_values = ["active", "inactive"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def count_per_lot(self):
        """Gets the count_per_lot of this Product.  # noqa: E501

        The number of items per lot   # noqa: E501

        :return: The count_per_lot of this Product.  # noqa: E501
        :rtype: int
        """
        return self._count_per_lot

    @count_per_lot.setter
    def count_per_lot(self, count_per_lot):
        """Sets the count_per_lot of this Product.

        The number of items per lot   # noqa: E501

        :param count_per_lot: The count_per_lot of this Product.  # noqa: E501
        :type: int
        """

        self._count_per_lot = count_per_lot

    @property
    def wish_list_count(self):
        """Gets the wish_list_count of this Product.  # noqa: E501

        Number of times the item has been added to a wishlist   # noqa: E501

        :return: The wish_list_count of this Product.  # noqa: E501
        :rtype: int
        """
        return self._wish_list_count

    @wish_list_count.setter
    def wish_list_count(self, wish_list_count):
        """Sets the wish_list_count of this Product.

        Number of times the item has been added to a wishlist   # noqa: E501

        :param wish_list_count: The wish_list_count of this Product.  # noqa: E501
        :type: int
        """

        self._wish_list_count = wish_list_count

    @property
    def unit(self):
        """Gets the unit of this Product.  # noqa: E501

        The unit of the item   # noqa: E501

        :return: The unit of this Product.  # noqa: E501
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this Product.

        The unit of the item   # noqa: E501

        :param unit: The unit of this Product.  # noqa: E501
        :type: str
        """

        self._unit = unit

    @property
    def multi_unit(self):
        """Gets the multi_unit of this Product.  # noqa: E501

        The unit for multiple items   # noqa: E501

        :return: The multi_unit of this Product.  # noqa: E501
        :rtype: str
        """
        return self._multi_unit

    @multi_unit.setter
    def multi_unit(self, multi_unit):
        """Sets the multi_unit of this Product.

        The unit for multiple items   # noqa: E501

        :param multi_unit: The multi_unit of this Product.  # noqa: E501
        :type: str
        """

        self._multi_unit = multi_unit

    @property
    def seller(self):
        """Gets the seller of this Product.  # noqa: E501


        :return: The seller of this Product.  # noqa: E501
        :rtype: ProductSeller
        """
        return self._seller

    @seller.setter
    def seller(self, seller):
        """Sets the seller of this Product.


        :param seller: The seller of this Product.  # noqa: E501
        :type: ProductSeller
        """

        self._seller = seller

    @property
    def reviews(self):
        """Gets the reviews of this Product.  # noqa: E501


        :return: The reviews of this Product.  # noqa: E501
        :rtype: ProductReviews
        """
        return self._reviews

    @reviews.setter
    def reviews(self, reviews):
        """Sets the reviews of this Product.


        :param reviews: The reviews of this Product.  # noqa: E501
        :type: ProductReviews
        """

        self._reviews = reviews

    @property
    def trade(self):
        """Gets the trade of this Product.  # noqa: E501


        :return: The trade of this Product.  # noqa: E501
        :rtype: TradeInformation
        """
        return self._trade

    @trade.setter
    def trade(self, trade):
        """Sets the trade of this Product.


        :param trade: The trade of this Product.  # noqa: E501
        :type: TradeInformation
        """

        self._trade = trade

    @property
    def promotion(self):
        """Gets the promotion of this Product.  # noqa: E501


        :return: The promotion of this Product.  # noqa: E501
        :rtype: ProductPromotion
        """
        return self._promotion

    @promotion.setter
    def promotion(self, promotion):
        """Sets the promotion of this Product.


        :param promotion: The promotion of this Product.  # noqa: E501
        :type: ProductPromotion
        """

        self._promotion = promotion

    @property
    def product_images(self):
        """Gets the product_images of this Product.  # noqa: E501

        The item images   # noqa: E501

        :return: The product_images of this Product.  # noqa: E501
        :rtype: list[str]
        """
        return self._product_images

    @product_images.setter
    def product_images(self, product_images):
        """Sets the product_images of this Product.

        The item images   # noqa: E501

        :param product_images: The product_images of this Product.  # noqa: E501
        :type: list[str]
        """

        self._product_images = product_images

    @property
    def attributes(self):
        """Gets the attributes of this Product.  # noqa: E501

        Attributes associated with the AliExpress product   # noqa: E501

        :return: The attributes of this Product.  # noqa: E501
        :rtype: list[ProductAttribute]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this Product.

        Attributes associated with the AliExpress product   # noqa: E501

        :param attributes: The attributes of this Product.  # noqa: E501
        :type: list[ProductAttribute]
        """

        self._attributes = attributes

    @property
    def html_description(self):
        """Gets the html_description of this Product.  # noqa: E501

        The product HTML description   # noqa: E501

        :return: The html_description of this Product.  # noqa: E501
        :rtype: str
        """
        return self._html_description

    @html_description.setter
    def html_description(self, html_description):
        """Sets the html_description of this Product.

        The product HTML description   # noqa: E501

        :param html_description: The html_description of this Product.  # noqa: E501
        :type: str
        """

        self._html_description = html_description

    @property
    def price_summary(self):
        """Gets the price_summary of this Product.  # noqa: E501


        :return: The price_summary of this Product.  # noqa: E501
        :rtype: PriceSummary
        """
        return self._price_summary

    @price_summary.setter
    def price_summary(self, price_summary):
        """Sets the price_summary of this Product.


        :param price_summary: The price_summary of this Product.  # noqa: E501
        :type: PriceSummary
        """

        self._price_summary = price_summary

    @property
    def prices(self):
        """Gets the prices of this Product.  # noqa: E501

        All the variations of an AliExpress item and prices associated with each variation   # noqa: E501

        :return: The prices of this Product.  # noqa: E501
        :rtype: list[SkuPriceOption]
        """
        return self._prices

    @prices.setter
    def prices(self, prices):
        """Sets the prices of this Product.

        All the variations of an AliExpress item and prices associated with each variation   # noqa: E501

        :param prices: The prices of this Product.  # noqa: E501
        :type: list[SkuPriceOption]
        """

        self._prices = prices

    @property
    def shipping(self):
        """Gets the shipping of this Product.  # noqa: E501

        The shipping options of an AliExpress item   # noqa: E501

        :return: The shipping of this Product.  # noqa: E501
        :rtype: list[ProductShippingOptions]
        """
        return self._shipping

    @shipping.setter
    def shipping(self, shipping):
        """Sets the shipping of this Product.

        The shipping options of an AliExpress item   # noqa: E501

        :param shipping: The shipping of this Product.  # noqa: E501
        :type: list[ProductShippingOptions]
        """

        self._shipping = shipping

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Product):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
