# coding: utf-8

"""
    Aliseeks API

    AliExpress product searching and product details retrieval API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ProductSkus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'variations': 'list[ProductSku]'
    }

    attribute_map = {
        'variations': 'variations'
    }

    def __init__(self, variations=None):  # noqa: E501
        """ProductSkus - a model defined in OpenAPI"""  # noqa: E501

        self._variations = None
        self.discriminator = None

        if variations is not None:
            self.variations = variations

    @property
    def variations(self):
        """Gets the variations of this ProductSkus.  # noqa: E501

        List of product pricing information   # noqa: E501

        :return: The variations of this ProductSkus.  # noqa: E501
        :rtype: list[ProductSku]
        """
        return self._variations

    @variations.setter
    def variations(self, variations):
        """Sets the variations of this ProductSkus.

        List of product pricing information   # noqa: E501

        :param variations: The variations of this ProductSkus.  # noqa: E501
        :type: list[ProductSku]
        """

        self._variations = variations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductSkus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
