# coding: utf-8

"""
    Aliseeks API

    AliExpress product searching and product details retrieval API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ProductAttribute(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'id': 'int',
        'value': 'str',
        'value_id': 'str'
    }

    attribute_map = {
        'name': 'name',
        'id': 'id',
        'value': 'value',
        'value_id': 'valueId'
    }

    def __init__(self, name=None, id=None, value=None, value_id=None):  # noqa: E501
        """ProductAttribute - a model defined in OpenAPI"""  # noqa: E501

        self._name = None
        self._id = None
        self._value = None
        self._value_id = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if id is not None:
            self.id = id
        if value is not None:
            self.value = value
        if value_id is not None:
            self.value_id = value_id

    @property
    def name(self):
        """Gets the name of this ProductAttribute.  # noqa: E501

        The name of the attribute   # noqa: E501

        :return: The name of this ProductAttribute.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProductAttribute.

        The name of the attribute   # noqa: E501

        :param name: The name of this ProductAttribute.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this ProductAttribute.  # noqa: E501

        The ID of the attribute   # noqa: E501

        :return: The id of this ProductAttribute.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProductAttribute.

        The ID of the attribute   # noqa: E501

        :param id: The id of this ProductAttribute.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def value(self):
        """Gets the value of this ProductAttribute.  # noqa: E501

        The value of the attribute   # noqa: E501

        :return: The value of this ProductAttribute.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ProductAttribute.

        The value of the attribute   # noqa: E501

        :param value: The value of this ProductAttribute.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def value_id(self):
        """Gets the value_id of this ProductAttribute.  # noqa: E501

        The ID of the value of the attribute   # noqa: E501

        :return: The value_id of this ProductAttribute.  # noqa: E501
        :rtype: str
        """
        return self._value_id

    @value_id.setter
    def value_id(self, value_id):
        """Sets the value_id of this ProductAttribute.

        The ID of the value of the attribute   # noqa: E501

        :param value_id: The value_id of this ProductAttribute.  # noqa: E501
        :type: str
        """

        self._value_id = value_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductAttribute):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
