# coding: utf-8

"""
    Aliseeks API

    AliExpress product searching and product details retrieval API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class RealtimeSearchAggregation(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'total_count': 'int',
        'ship_from_countries': 'list[str]'
    }

    attribute_map = {
        'total_count': 'totalCount',
        'ship_from_countries': 'shipFromCountries'
    }

    def __init__(self, total_count=None, ship_from_countries=None):  # noqa: E501
        """RealtimeSearchAggregation - a model defined in OpenAPI"""  # noqa: E501

        self._total_count = None
        self._ship_from_countries = None
        self.discriminator = None

        if total_count is not None:
            self.total_count = total_count
        if ship_from_countries is not None:
            self.ship_from_countries = ship_from_countries

    @property
    def total_count(self):
        """Gets the total_count of this RealtimeSearchAggregation.  # noqa: E501

        The total number of items that matched the request   # noqa: E501

        :return: The total_count of this RealtimeSearchAggregation.  # noqa: E501
        :rtype: int
        """
        return self._total_count

    @total_count.setter
    def total_count(self, total_count):
        """Sets the total_count of this RealtimeSearchAggregation.

        The total number of items that matched the request   # noqa: E501

        :param total_count: The total_count of this RealtimeSearchAggregation.  # noqa: E501
        :type: int
        """

        self._total_count = total_count

    @property
    def ship_from_countries(self):
        """Gets the ship_from_countries of this RealtimeSearchAggregation.  # noqa: E501

        The countries that the items can ship from   # noqa: E501

        :return: The ship_from_countries of this RealtimeSearchAggregation.  # noqa: E501
        :rtype: list[str]
        """
        return self._ship_from_countries

    @ship_from_countries.setter
    def ship_from_countries(self, ship_from_countries):
        """Sets the ship_from_countries of this RealtimeSearchAggregation.

        The countries that the items can ship from   # noqa: E501

        :param ship_from_countries: The ship_from_countries of this RealtimeSearchAggregation.  # noqa: E501
        :type: list[str]
        """

        self._ship_from_countries = ship_from_countries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RealtimeSearchAggregation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
