# coding: utf-8

"""
    Aliseeks API

    AliExpress product searching and product details retrieval API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class RealtimeSearchResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'aggregation': 'RealtimeSearchAggregation',
        'items': 'list[RealtimeSearchItem]'
    }

    attribute_map = {
        'aggregation': 'aggregation',
        'items': 'items'
    }

    def __init__(self, aggregation=None, items=None):  # noqa: E501
        """RealtimeSearchResponse - a model defined in OpenAPI"""  # noqa: E501

        self._aggregation = None
        self._items = None
        self.discriminator = None

        if aggregation is not None:
            self.aggregation = aggregation
        if items is not None:
            self.items = items

    @property
    def aggregation(self):
        """Gets the aggregation of this RealtimeSearchResponse.  # noqa: E501


        :return: The aggregation of this RealtimeSearchResponse.  # noqa: E501
        :rtype: RealtimeSearchAggregation
        """
        return self._aggregation

    @aggregation.setter
    def aggregation(self, aggregation):
        """Sets the aggregation of this RealtimeSearchResponse.


        :param aggregation: The aggregation of this RealtimeSearchResponse.  # noqa: E501
        :type: RealtimeSearchAggregation
        """

        self._aggregation = aggregation

    @property
    def items(self):
        """Gets the items of this RealtimeSearchResponse.  # noqa: E501

        The items from a realtime search   # noqa: E501

        :return: The items of this RealtimeSearchResponse.  # noqa: E501
        :rtype: list[RealtimeSearchItem]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this RealtimeSearchResponse.

        The items from a realtime search   # noqa: E501

        :param items: The items of this RealtimeSearchResponse.  # noqa: E501
        :type: list[RealtimeSearchItem]
        """

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RealtimeSearchResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
