# coding: utf-8

"""
    Aliseeks API

    AliExpress product searching and product details retrieval API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class RealtimeSearchItem(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'image_url': 'str',
        'title': 'str',
        'ratings': 'float',
        'orders': 'int',
        'freight': 'SearchItemFreight',
        'price_options': 'list[SearchPriceOption]'
    }

    attribute_map = {
        'id': 'id',
        'image_url': 'imageUrl',
        'title': 'title',
        'ratings': 'ratings',
        'orders': 'orders',
        'freight': 'freight',
        'price_options': 'priceOptions'
    }

    def __init__(self, id=None, image_url=None, title=None, ratings=None, orders=None, freight=None, price_options=None):  # noqa: E501
        """RealtimeSearchItem - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._image_url = None
        self._title = None
        self._ratings = None
        self._orders = None
        self._freight = None
        self._price_options = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if image_url is not None:
            self.image_url = image_url
        if title is not None:
            self.title = title
        if ratings is not None:
            self.ratings = ratings
        if orders is not None:
            self.orders = orders
        if freight is not None:
            self.freight = freight
        if price_options is not None:
            self.price_options = price_options

    @property
    def id(self):
        """Gets the id of this RealtimeSearchItem.  # noqa: E501

        The AliExpress product ID   # noqa: E501

        :return: The id of this RealtimeSearchItem.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RealtimeSearchItem.

        The AliExpress product ID   # noqa: E501

        :param id: The id of this RealtimeSearchItem.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def image_url(self):
        """Gets the image_url of this RealtimeSearchItem.  # noqa: E501

        The image URL for the item   # noqa: E501

        :return: The image_url of this RealtimeSearchItem.  # noqa: E501
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url):
        """Sets the image_url of this RealtimeSearchItem.

        The image URL for the item   # noqa: E501

        :param image_url: The image_url of this RealtimeSearchItem.  # noqa: E501
        :type: str
        """

        self._image_url = image_url

    @property
    def title(self):
        """Gets the title of this RealtimeSearchItem.  # noqa: E501

        The subject / title of the item   # noqa: E501

        :return: The title of this RealtimeSearchItem.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this RealtimeSearchItem.

        The subject / title of the item   # noqa: E501

        :param title: The title of this RealtimeSearchItem.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def ratings(self):
        """Gets the ratings of this RealtimeSearchItem.  # noqa: E501

        The ratings of the item   # noqa: E501

        :return: The ratings of this RealtimeSearchItem.  # noqa: E501
        :rtype: float
        """
        return self._ratings

    @ratings.setter
    def ratings(self, ratings):
        """Sets the ratings of this RealtimeSearchItem.

        The ratings of the item   # noqa: E501

        :param ratings: The ratings of this RealtimeSearchItem.  # noqa: E501
        :type: float
        """

        self._ratings = ratings

    @property
    def orders(self):
        """Gets the orders of this RealtimeSearchItem.  # noqa: E501

        The number of orders of the item   # noqa: E501

        :return: The orders of this RealtimeSearchItem.  # noqa: E501
        :rtype: int
        """
        return self._orders

    @orders.setter
    def orders(self, orders):
        """Sets the orders of this RealtimeSearchItem.

        The number of orders of the item   # noqa: E501

        :param orders: The orders of this RealtimeSearchItem.  # noqa: E501
        :type: int
        """

        self._orders = orders

    @property
    def freight(self):
        """Gets the freight of this RealtimeSearchItem.  # noqa: E501


        :return: The freight of this RealtimeSearchItem.  # noqa: E501
        :rtype: SearchItemFreight
        """
        return self._freight

    @freight.setter
    def freight(self, freight):
        """Sets the freight of this RealtimeSearchItem.


        :param freight: The freight of this RealtimeSearchItem.  # noqa: E501
        :type: SearchItemFreight
        """

        self._freight = freight

    @property
    def price_options(self):
        """Gets the price_options of this RealtimeSearchItem.  # noqa: E501

        The price options for the item   # noqa: E501

        :return: The price_options of this RealtimeSearchItem.  # noqa: E501
        :rtype: list[SearchPriceOption]
        """
        return self._price_options

    @price_options.setter
    def price_options(self, price_options):
        """Sets the price_options of this RealtimeSearchItem.

        The price options for the item   # noqa: E501

        :param price_options: The price_options of this RealtimeSearchItem.  # noqa: E501
        :type: list[SearchPriceOption]
        """

        self._price_options = price_options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RealtimeSearchItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
