# coding: utf-8

"""
    Aliseeks API

    AliExpress product searching and product details retrieval API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SearchPriceOption(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'original_amount': 'Amount',
        'amount': 'Amount'
    }

    attribute_map = {
        'type': 'type',
        'original_amount': 'originalAmount',
        'amount': 'amount'
    }

    def __init__(self, type=None, original_amount=None, amount=None):  # noqa: E501
        """SearchPriceOption - a model defined in OpenAPI"""  # noqa: E501

        self._type = None
        self._original_amount = None
        self._amount = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if original_amount is not None:
            self.original_amount = original_amount
        if amount is not None:
            self.amount = amount

    @property
    def type(self):
        """Gets the type of this SearchPriceOption.  # noqa: E501

        The type of the price, either pc_price or app_price   # noqa: E501

        :return: The type of this SearchPriceOption.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SearchPriceOption.

        The type of the price, either pc_price or app_price   # noqa: E501

        :param type: The type of this SearchPriceOption.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def original_amount(self):
        """Gets the original_amount of this SearchPriceOption.  # noqa: E501


        :return: The original_amount of this SearchPriceOption.  # noqa: E501
        :rtype: Amount
        """
        return self._original_amount

    @original_amount.setter
    def original_amount(self, original_amount):
        """Sets the original_amount of this SearchPriceOption.


        :param original_amount: The original_amount of this SearchPriceOption.  # noqa: E501
        :type: Amount
        """

        self._original_amount = original_amount

    @property
    def amount(self):
        """Gets the amount of this SearchPriceOption.  # noqa: E501


        :return: The amount of this SearchPriceOption.  # noqa: E501
        :rtype: Amount
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this SearchPriceOption.


        :param amount: The amount of this SearchPriceOption.  # noqa: E501
        :type: Amount
        """

        self._amount = amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchPriceOption):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
