# coding: utf-8

"""
    Aliseeks API

    AliExpress product searching and product details retrieval API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class UploadImageResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'upload_key': 'str'
    }

    attribute_map = {
        'upload_key': 'uploadKey'
    }

    def __init__(self, upload_key=None):  # noqa: E501
        """UploadImageResponse - a model defined in OpenAPI"""  # noqa: E501

        self._upload_key = None
        self.discriminator = None

        if upload_key is not None:
            self.upload_key = upload_key

    @property
    def upload_key(self):
        """Gets the upload_key of this UploadImageResponse.  # noqa: E501

        The upload key that should be used when performing an image search request   # noqa: E501

        :return: The upload_key of this UploadImageResponse.  # noqa: E501
        :rtype: str
        """
        return self._upload_key

    @upload_key.setter
    def upload_key(self, upload_key):
        """Sets the upload_key of this UploadImageResponse.

        The upload key that should be used when performing an image search request   # noqa: E501

        :param upload_key: The upload_key of this UploadImageResponse.  # noqa: E501
        :type: str
        """

        self._upload_key = upload_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UploadImageResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
